# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b71c114f083870d017bd6366d81087d8bb91ef0bfa4eecf8d7a9b0663745a3a7ce9614c6176a22cb9f9e1b89b1f79e789bda35187fda7d53db370f375b760a72

test:
  secret_key_base: 7c34aa184930035ab090737046ab0b2d8d123434ca787b737842781ee0e585b0f19e3a28441d1304f4742c2ecccd51a0aa625ed00c8a85cd54c0ec957064b764

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
